In [1]:
import pandas as pd 
import numpy as np

In [3]:
#Load data set 
df = pd.read_csv(r'D:\DataScienceAndAICourse\March-Month\18th - ML\TITANIC PROJECT\DATASET\Salary_Data.csv')

In [5]:
df.mean()

YearsExperience        5.313333
Salary             76003.000000
dtype: float64

In [7]:
df.head()

   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [9]:
df['Salary'].mean()

76003.0

In [11]:
df.median()

YearsExperience        4.7
Salary             65237.0
dtype: float64

In [13]:
df['Salary'].median()

65237.0

In [16]:
df['Salary'].mode()

0      37731
1      39343
2      39891
3      43525
4      46205
5      54445
6      55794
7      56642
8      56957
9      57081
10     57189
11     60150
12     61111
13     63218
14     64445
15     66029
16     67938
17     81363
18     83088
19     91738
20     93940
21     98273
22    101302
23    105582
24    109431
25    112635
26    113812
27    116969
28    121872
29    122391
Name: Salary, dtype: int64

In [18]:
df.var()

YearsExperience    8.053609e+00
Salary             7.515510e+08
dtype: float64

In [22]:
df['Salary'].var()

751550960.4137931

In [24]:
df.std()

YearsExperience        2.837888
Salary             27414.429785
dtype: float64

In [26]:
df['Salary'].std()

27414.4297845823

In [30]:
from scipy.stats import variation 
variation(df.values)

array([0.5251297 , 0.35463929])

In [33]:
variation(df['Salary'])

0.3546392938275572

In [35]:
df.corr()

                 YearsExperience    Salary
YearsExperience         1.000000  0.978242
Salary                  0.978242  1.000000

In [37]:
df['Salary'].corr(df['YearsExperience'])

0.9782416184887598

In [39]:
df.skew()

YearsExperience    0.37956
Salary             0.35412
dtype: float64

In [41]:
df['Salary'].skew()

0.35411967922959153

In [43]:
df.sem()

YearsExperience       0.518125
Salary             5005.167198
dtype: float64

In [45]:
df['Salary'].sem()

5005.167198052405

In [49]:
import scipy.stats as stats 
df.apply(stats.zscore)

    YearsExperience    Salary
0         -1.510053 -1.360113
1         -1.438373 -1.105527
2         -1.366693 -1.419919
3         -1.187494 -1.204957
4         -1.115814 -1.339781
5         -0.864935 -0.718307
6         -0.829096 -0.588158
7         -0.757416 -0.799817
8         -0.757416 -0.428810
9         -0.578216 -0.698013
10        -0.506537 -0.474333
11        -0.470697 -0.749769
12        -0.470697 -0.706620
13        -0.434857 -0.702020
14        -0.291498 -0.552504
15        -0.148138 -0.299217
16        -0.076458 -0.370043
17        -0.004779  0.262859
18         0.210261  0.198860
19         0.246100  0.665476
20         0.532819  0.583780
21         0.640339  0.826233
22         0.927058  0.938611
23         1.034577  1.402741
24         1.213777  1.240203
25         1.321296  1.097402
26         1.500496  1.519868
27         1.536336  1.359074
28         1.787215  1.721028
29         1.858894  1.701773

In [51]:
stats.zscore(df['Salary'])

0    -1.360113
1    -1.105527
2    -1.419919
3    -1.204957
4    -1.339781
5    -0.718307
6    -0.588158
7    -0.799817
8    -0.428810
9    -0.698013
10   -0.474333
11   -0.749769
12   -0.706620
13   -0.702020
14   -0.552504
15   -0.299217
16   -0.370043
17    0.262859
18    0.198860
19    0.665476
20    0.583780
21    0.826233
22    0.938611
23    1.402741
24    1.240203
25    1.097402
26    1.519868
27    1.359074
28    1.721028
29    1.701773
Name: Salary, dtype: float64

In [53]:
a= df.shape[0]
b=df.shape[1]
degree_of_freedom = a-b 
print('degree_of_freedom',degree_of_freedom)

degree_of_freedom 28

In [67]:
x= df.iloc[:,:-1].values
y =df.iloc[:,1].values

y_mean = np.mean(y)
from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=0)
from sklearn.linear_model import LinearRegression 
reg = LinearRegression()
reg.fit(x_train,y_train)

y_pred= reg.predict(x_test)

SSR = np.sum((y_pred - y_mean)**2)
print(SSR)

6263152884.284127

In [75]:
x=df.iloc[:,:-1].values
y=df.iloc[:,1].values

from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=0)
from sklearn.linear_model import LinearRegression
reg =LinearRegression()
reg.fit(x_train,y_train)

y_pred = reg.predict(x_test)
y = y[0:6]
SSE = np.sum((y-y_pred)**2)

print(SSE)

15274062883.9432

In [77]:
SSR + SSE

21537215768.227325

In [86]:
mean_total = np.mean(df.values)
SST = np.sum((df.values - mean_total)**2)
SST

6430367737.0

In [84]:
RSQURE = 1 - (SSR/SSE)
RSQURE

0.5899484680747096